### ISSUE TITLE
It's hard for a build script to put pb-rs output in OUT_DIR

### ISSUE THREAD

**Issue by jimblandy** [tafia/quick-protobuf#122]
The `cargo package` command checks that the build script doesn't modify the source directory; as the Cargo book [explains][cb], build scripts are not supposed to modify anything outside the directory given in the `OUT_DIR` environment variable.

This rule is hard to follow when calling `pb-rs` from `build.rs`: the only way I'm aware of to incorporate code from OUT_DIR is via an `include!` directive, but that chokes on the `//!` comments that `pb-rs` places at the top of its generated files. When I write:

```
mod mozilla {
include!(concat!(env!("OUT_DIR"), "/mozilla/mod.rs"))
}
```
rustc complains:
```
error: macros that expand to items must either be surrounded with braces or followed by a semicolon
 --> src/dump/mod.rs:7:9
  |
7 | include!(concat!(env!("OUT_DIR"), "/mozilla/mod.rs"))
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

[cb]: https://doc.rust-lang.org/cargo/reference/build-scripts.html

**Comment by jimblandy** [comment]
Note that the `#[path]` attribute on modules doesn't seem to do macro expansion on its argument, so something like
```
#[path=concat!(env!("OUT_DIR"), "/mozilla/mod.rs")]
mod mozilla;
```
doesn't work either.

**Comment by jimblandy** [comment]
It's arguably a Rust bug that `include!` is incapable of incorporating text with `//!` comments. Fixing that would make this problem go away.

**Comment by tafia** [comment]
We can probably (optionally) remove the comments from generated file. There are not strictly required.

**Comment by tafia** [comment]
Alright, so I made it work by not generating all the headers at all.
So I'll put all the [`write_headers`](https://github.com/tafia/quick-protobuf/blob/master/pb-rs/src/types.rs#L1752) function as optional in config.
I'll also update the readme for build.rs
