### ISSUE TITLE
Some Examples would be Cool

### ISSUE THREAD

**Issue by stevedonovan** [tafia/quick-protobuf#13]
Just to get a feel for how the API is put together. More docs, of course, but examples go a long way.

**Comment by tafia** [comment]
Yes I totally agree. This is definitely on my to-do list. I'll add some tomorrow.

**Comment by stevedonovan** [comment]
Even if just on github for now, because 'examples' folder implies something that can be built with Cargo.

**Comment by tafia** [comment]
Here is what has been done so far:
- [updated](2187e7f4e7f7399fe7db58dbe0beed293847c003) the readme to have a basic example (reader).
- [updated](176e74dba5cb369edf227942854fa72cc5b5638c) the `reader` module documentation
- [updated](1dce58ffbfa4df4808878832223a5e5418391771) the `writer` module documentation
- added a benches directory with some examples (not the easiest to read): [perftest.rs](benches/perftest.rs)

**Comment by tafia** [comment]
I will soon add Examples directory but this should be a good start.
@stevedonovan do you have something else in mind?

**Comment by stevedonovan** [comment]
Yes, that's starting to look good. I would suggest the main example use a protobuf which has examples of more kinds of fields, so that we can see the generated API.

BTW, your links are pointing nowhere, alas.

**Comment by tafia** [comment]
> BTW, your links are pointing nowhere, alas

Fixed

Thanks for your feedback!

**Comment by tafia** [comment]
I've pushed some more details about all field conversions:
https://github.com/tafia/quick-protobuf/commit/ce964defa859ed1fb5eab8bcc3849f35245ce69c

**Comment by tafia** [comment]
Closing with #21, let me know if something is still missing in your opinion

**Comment by stevedonovan** [comment]
Looks good, works as advertised!  I found I could run `codegen_example.rs` by creating an `example` folder and copying it there - then `cargo run --example codegen_example` works fine. I suppose you could put everything in `example` (the canonical folder) but then would need a custom build.rs step to do codegen and so forth.  The generated code really is simple.

**Comment by tafia** [comment]
> Looks good, works as advertised!

Glad to read this!

> I suppose you could put everything in example

Actually it breaks `cargo test` because cargo tries running each file and do not understand they are a module and not a root file (not sure I'm clear).

**Comment by stevedonovan** [comment]
Oh I remember that! No doubt there's a clever way to get around this, but current `examples` works just fine, after the copy. I'm always impressed with the amount of work necessary to get a crate easily accessible by everyone else, so thanks.

**Comment by tafia** [comment]
I'm not sure I understand your point regarding `example` folder.
On my side it works fine with the `examples` folder (as suggested [here](http://doc.crates.io/manifest.html#the-project-layout)) without copying anything.

**Comment by stevedonovan** [comment]
Hah, well I did get tangled up there! You are quite right, `examples` is the canonical folder. And it works for me, when I leave my preconceptions out of the way.

**Comment by tafia** [comment]
😉
