### ISSUE TITLE
The bytes generated by calling serialize_into_slice under no_std are one bit more than the bytes generated by serializing under js and go

### ISSUE THREAD

**Issue by malefooo** [tafia/quick-protobuf#185]
![image](https://user-images.githubusercontent.com/31642966/104585010-64bf1d00-569e-11eb-8f97-1db2976f27ba.png)
The bytes generated by calling serialize_into_slice under no_std are one bit more than the bytes generated by serializing under js and go,Moreover, it seems that the longer the message, the more digits increase in the head.
@nerdrew 
my serialize code
![image](https://user-images.githubusercontent.com/31642966/104585212-afd93000-569e-11eb-84db-5a420cb11130.png)

**Comment by valnesfjord** [comment]
same problem, but for serialize_into_vec,  how to fix?
