### ISSUE TITLE
Mark deprecated fields instead of ignoring them

### ISSUE THREAD

**Issue by yzsolt** [tafia/quick-protobuf#189]
Currently all deprecated Proto fields are ignored when generating Rust code, making them inaccessible. I think this isn't the right thing to do, they should be marked with `#[deprecated]` instead ([documentation](https://doc.rust-lang.org/edition-guide/rust-2018/the-compiler/an-attribute-for-deprecation.html)).

If you agree, I'm up for making the necessary changes.

**Comment by tafia** [comment]
I agree in principle but I don't really like code bloat.
Could you make it as optional?
