### ISSUE TITLE
codegen issue for repeated strings

### ISSUE THREAD

**Issue by stevedonovan** [tafia/quick-protobuf#38]
They are indeed vectors of Cows, but when reading them we don't do the `.map(Cow::Borrowed)` necessary to get the returned `&str` from `read_string` into the correct type.

**Comment by tafia** [comment]
Do you get a compile error?
I'll add a test and fix it

**Comment by stevedonovan** [comment]
Yep, I got a compile error, but it was easy to 'fix' by reference to how plain strings are handled. I suppose you could simplify your codegen by defining `read_string_cow` as well.

**Comment by tafia** [comment]
I cannot reproduce the issue. Perhaps I have fixed it already, i don't know.

For instance, on the coming PR on tests, [this tests](https://github.com/tafia/quick-protobuf/pull/44/files#diff-dc27acc3726a5481c6be2486fd98d2c9R105) passes. Which means it is generated properly, compiles then the test is ok.

Could you provide me with a .proto file example which doesn't work on your side?

**Comment by stevedonovan** [comment]
Interesting! I'll have a look at it tonight, after pulling.

**Comment by stevedonovan** [comment]
It's definitely fixed!  So false alarm there - oneof issue sorted as well.

**Comment by tafia** [comment]
Thanks a lot for your tests !
