### ISSUE TITLE
When to support protobuf 3.x ?

### ISSUE THREAD

**Issue by kingxsp** [tafia/quick-protobuf#47]

**Comment by tafia** [comment]
Could you tell me which feature exactly you are looking for?
Most of Protobuf 3 should be ok already (as long as the `syntax = "proto3"` is mentionned)

**Comment by tafia** [comment]
I just published a version 0.4.0. Perhaps what's you're looking for is there?
I'll publish a cargo tool for the codegen probably next week (so you won't need to clone the repo anymore)
