### ISSUE TITLE
Cannot upgrade to error-chain 0.10.0

### ISSUE THREAD

**Issue by tafia** [tafia/quick-protobuf#58]
See https://github.com/Arnavion/derive-error-chain/issues/12

error-chain removed the `Sync` bound of `Error`, thus we cannot convert it to `io::Error`.
Waiting for a solution on error-chain side. If nothing happens, then we may find a solution.

**Comment by stevedonovan** [comment]
That's a big change, since `io::Error` is _everywhere_. Can always be chained, I suppose.

**Comment by tafia** [comment]
Not sure.
I'm expecting to see a solution/workaround on error-chain side

**Comment by tafia** [comment]
I plan on migrating both quick-protobuf and pb-rs to failure asap.
