### ISSUE TITLE
Length prefix is 8 bits, but shouldn't it be 32?

### ISSUE THREAD

**Issue by CraigglesO** [tafia/quick-protobuf#66]
Not a big deal, I have yet to have an issue because the device I am working with has yet to need more than 8 bits for sending a message, however, the device uses a 32bit structure for sending and receiving and I can only assume that is how google's protobuf works.

This is an example write:
`[63, 35, 35, 0, 29, 0, 0, 0, 12, 18, 8, 69, 116, 104, 101, 114, 101, 117, 109, 24, 1]`

Notice, `[0, 29]` is the code and `[0, 0, 0, 12]` is the send... so I am adding [0, 0, 0] prior to the `12`.

I'll try to look into this more to ensure that google protobuf requires this.

**Comment by tafia** [comment]
>  I can only assume that is how google's protobuf works.

Not really. The length is generally encoded with [base 128 Varint](https://developers.google.com/protocol-buffers/docs/encoding#varints). I understand that the issue has been opened long ago but do you remember having an issue?
