### ISSUE TITLE
Codegen:  `packed` should work only for primitive numeric fields

### ISSUE THREAD

**Issue by neivv** [tafia/quick-protobuf#68]
From https://developers.google.com/protocol-buffers/docs/encoding#packed

> Only repeated fields of primitive numeric types (types which use the varint, 32-bit, or 64-bit wire types) can be declared "packed".

This is pretty bad when using proto3 syntax as the generated code is incorrectly using packed on any repeated string / embedded message field.

**Comment by tafia** [comment]
I didn't see that ... this is problematic indeed!
