### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by Trolldemorted** [tafia/quick-protobuf#72]
It has already been mentioned on reddit, but there wasn't an issue yet: `no_std` would naturally be great for embedded and driver development!

**Comment by jbowens** [comment]
+1

**Comment by jbowens** [comment]
One obstacle might be the error-chain dependency which [does not support no_std](https://github.com/rust-lang-nursery/error-chain/issues/138)

**Comment by lexxvir** [comment]
+1

**Comment by tafia** [comment]
Just to let you know that I have just merged the pr to migrate to failure. It should help moving towards no_std

**Comment by benma** [comment]
What's the status on this? Is this crate `no_std` compatible? If not, would it be easy to change?

**Comment by tafia** [comment]
Merged!
