### ISSUE TITLE
Lifetime design problem for Read object.

### ISSUE THREAD

**Issue by sashao** [tafia/quick-protobuf#84]
Hi, 
In my case I have a stream and need to read protobuf messages along with raw data.

|message|data|message|data|...|

Once I created Read object for my stream 
`Reader::from_reader<R: Read>(mut r: R, capacity: usize) `
it !moves! ownership to  protobuf Reader object so that stream Read object can't be used anymore.

protobbuf-Reader can't release ownersip in any way, and deletes stream-Reader in the end.

Could you please change protobuf reader to borrow reader?

`from_reader<R: Read>(mut& r: R, capacity: usize)`

**Comment by tafia** [comment]
The std have you covered here:
```rust
impl<'a, R: Read + ?Sized> Read for &'a mut R
```

Which means instead of using `reader`, use `&mut reader` and it should be good.

**Comment by sashao** [comment]
Thnks for help!
