### ISSUE TITLE
Need help: read messages of unknown size from stream

### ISSUE THREAD

**Issue by sashao** [tafia/quick-protobuf#87]
I might be missing something, and need some help.
Reader type has 3 constructor each working only with data of predefined size.
https://github.com/tafia/quick-protobuf/blob/4894db64d8f157fbb97e9f3c2ccb81c8e0377b52/src/reader.rs#L514-L543
Please adwise: For situation where there is a stream and I have to read different messages and raw data from it. ( http://wiki.openstreetmap.org/wiki/PBF_Format#File_format )

How to use quick-protobuf correctly? 
```
- read message 1 of unknown size
- read raw data
- read message 2 of unknown size
````

**Comment by tafia** [comment]
I didn't see this issue, sorry!
I guess you figured out what was happening or decided to go for another library (sorry for that).
