### ISSUE TITLE
Consider publishing `pb-rs` to crates.io so that it can be `cargo install`ed

### ISSUE THREAD

**Issue by nbigaouette-eai** [tafia/quick-protobuf#88]
It would make a lot of sense to publish `pb-rs` to crates.io in a format that can then be installed using `cargo install pb-rs`.

I was surprised to have to git clone the repo and run it from there.

This would make it easier to use, specially in a Dockerfile.

**Comment by tafia** [comment]
Done.
I'll work on having a library compatible version as well (see #73)
