### ISSUE TITLE
Encoded data can not be deserialized

### ISSUE THREAD

**Issue by SergejJurecko** [tafia/quick-protobuf#89]
I created a simple project to demonstrate the issue: https://github.com/SergejJurecko/qptest/

If you checkout and try:

    make run
    make check

It will fail.

if you try creating the same structure with protoc it will work:

    make protoc
    make check

**Comment by SergejJurecko** [comment]
I see I must use mymsg.write_message(&mut writer) instead of writer.write_message(&mymsg). This will work with protoc and other protobuf implementations (namely erlang gpb).

Going through writer will prepend a message size. In what situation is this valid?

**Comment by tafia** [comment]
The names are confusing we should probably change that, I'll have a look.
One is writing the message itself the other one the message plus its length.
