### ISSUE TITLE
Cannot generate from Mesos protobufs.

### ISSUE THREAD

**Issue by jeschkies** [tafia/quick-protobuf#90]
I tried to use `quick-protobuf` for the [Mesos](https://github.com/apache/mesos/tree/master/include/mesos/v1) protocol buffers but the generation fails.

It cannot find some enums from `mesos.proto`. I switched to [rust-protobuf](https://github.com/stepancheg/rust-protobuf) and the generation works.

**Comment by tafia** [comment]
What error do you have in particular?
Can you share you have the .proto file ?

**Comment by jeschkies** [comment]
So, I have `mesos.proto` and `scheduler.proto` from the [Mesos master](https://github.com/apache/mesos/tree/master/include/mesos/v1). And this structure

```
› tree mesos
mesos
└── v1
    ├── mesos.proto
    └── scheduler
        └── scheduler.proto
```

I call `/pb-rs mesos/v1/mesos.proto mesos/v1/scheduler/scheduler.proto` from the parent of `mesos` I get

```
Error: Could not convert mesos/v1/mesos.proto into mesos/v1/mesos.rs
Caused by: Could not find enum CFQ.Statistics in [Enumerator ...]
```

**Comment by tafia** [comment]
It's been a long time but this issue should now be resolved.
I have added the mesos.proto file in the test suite.

Sorry for this, I had too many things on my hand.

Let me know (if you have time) if something looks wrong to you.
